import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex bg-[#050505] text-white">
        <aside className="w-64 border-r border-white/10 p-4">Sidebar</aside>
        <main className="flex-1 flex flex-col">
          <div className="flex-1">{children}</div>
          <footer className="h-16 border-t border-white/10 p-4">Bottom Bar</footer>
        </main>
      </body>
    </html>
  );
}
